Update `RESTDataSource` and `HTTPCache` for Apollo Server v4
apollographql/datasource-rest pull request #1
Opened 2022-08-08 19:50 UTC by trevor-scheer

Update the `RESTDataSource` class to be compatible with Apollo Server v4's new approach to datasources. This means initialization happens in the constructor (there's no more magic call to `initialize` done by Apollo Server).

Migrate to our `Fetcher` interface (and related types). This is a bit "restrictive" in that it doesn't accept the `Request` class from `node-fetch`, but the signature should be more cross compatible with other fetch implementation.

Remove `apollo-server-env` completely, update tests to use nock.

2022-08-08 20:11 UTC, trevor-scheer commented
Fixes https://github.com/apollographql/apollo-server/issues/6048

2022-08-08 21:03 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +  method?: 'POST' | 'PUT' | 'PATCH' | 'DELETE';
I don't think DELETE should allow a body

2022-08-08 22:41 UTC, glasser commented on src/RESTDataSource.ts
> +  method?: 'POST' | 'PUT' | 'PATCH' | 'DELETE';
Looks like it's actually legit-ish https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

2022-08-08 22:42 UTC, glasser commented on package.json
>      "watch": "tsc --build --watch"
@trevor-scheer Many fields at the top of this file need to be updated (notably `name`, `description`, urls, etc)

2022-08-08 23:02 UTC, glasser requested changes

2022-08-08 23:02 UTC, glasser commented on src/index.ts
>  export { HTTPCache } from './HTTPCache';
Does this actually need to be publicly exported?

2022-08-08 23:05 UTC, glasser commented on package.json
> +    "http-cache-semantics": "^4.1.0"
I think there's a bunch of missing deps here: `node-fetch`, `@apollo/utils.fetcher`, `@apollo/utils.keyvaluecache`

2022-08-09 01:03 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +  params?: URLSearchParamsInit;
That's correct, though kind of surprising as I look more closely.

It looks like the fetch API allows `body` to be a `URLSearchParams`?
https://developer.mozilla.org/en-US/docs/Web/API/Request#examples

Maybe I'm going about this wrong by creating a distinction? The two types that I originally split (`GetRequest` and `RequestWithBody`) would theoretically collapse to just the one type if I treated search params as a body.

Idk, that seems a little weird and overloaded to me.

2022-08-09 01:04 UTC, trevor-scheer commented on package.json
> +    "http-cache-semantics": "^4.1.0"
8130df568b051808b0d7a4c2f66232d6683fa97b

2022-08-09 01:04 UTC, trevor-scheer commented on package.json
>      "watch": "tsc --build --watch"
8130df568b051808b0d7a4c2f66232d6683fa97b

2022-08-09 01:04 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +type URLSearchParamsInit = ConstructorParameters<typeof URLSearchParams>[0];
d18a6ce9302c1915c0c39a84cc098d5c1d9bec10

2022-08-09 01:04 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +    url: string,
Let me know what you think: bed450e6143b21d2c3645047bb2c8b4d0f183826

I think this mostly comes down to convenience and signature matching. As things get closer to the `Fetcher`, using a `string` is more natural.

2022-08-09 01:04 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +    if (!(modifiedRequest.params instanceof URLSearchParams)) {
Yep. This took me down a little rabbit hole, curious what you think.
b25c880

2022-08-09 01:04 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +  protected resolveURL(path: string): ValueOrPromise<URL> {
Are you looking to not break the existing API here or just ensure the same information that was previously available continue to be? `path` isn't on `RequestOptions` anymore. I can merge to make a single object (preserve existing API), which I've kind of avoided doing throughout / in other places.

Here's what I have (which just ensures previous information continues to be available)
352c298

2022-08-09 01:05 UTC, trevor-scheer commented on src/index.ts
>  export { HTTPCache } from './HTTPCache';
b25c880df0c1d881410c64019e2642bd07e47ed6

2022-08-10 00:21 UTC, glasser commented on src/RESTDataSource.ts
> +  params?: URLSearchParamsInit;
I believe that literally does put the URLSearchParams in the body, with an appropriate content-type of `application/x-www-form-urlencoded`. https://fetch.spec.whatwg.org/#bodyinit-unions

This is actually the thing that POST <form>s do by default! https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-enctype

so not really relevant to controlling the actual URL params.

2022-08-10 00:21 UTC, glasser commented on src/RESTDataSource.ts
> +    url: string,
Sure. Just thinking that for *protected* (overridable) methods it makes sense to be consistent rather than minimalist.

2022-08-10 00:25 UTC, glasser commented on src/RESTDataSource.ts
> +  protected resolveURL(path: string): ValueOrPromise<URL> {
The latter (for subclasses), so that change looks good.

2022-08-10 00:25 UTC, glasser approved these changes
I haven't super carefully reviewed the README but the rest looks good!

2022-08-18 21:34 UTC, merged