Replace infinite memoization with concurrent deduplication
apollographql/datasource-rest pull request #100
Opened 2022-11-24 01:27 UTC by glasser

RESTDataSource contained a memoization cache (separate from the HTTP-header-sensitive shared cache) which caches all GET requests forever. This wasn't even documented for the first four years of RESTDataSource's existence and led to a lot of confusion.

In this new major version, this cache will instead by default only de-duplicate *concurrent* GET requests.

This also introduces `deduplicationPolicyFor()` which lets you tune how de-duplication works, including restoring v4 semantics (see the changeset for code snippets).

Fixes #40.
Fixes #72.
Fixes #73.
Fixes #46.

Maybe fi-xes #39 but we could use a unit test.

Somewhat addresses #65 but only for the de-duplication cache (we should still allow direct control over the cache key for the HTTP).

2022-11-24 01:28 UTC, glasser commented
I should add a unit test for #39 because I think it fixes it (because I'm pretty sure http-cache-semantics is smart enough to not cache 302s).

2022-11-28 20:02 UTC, glasser commented
Added a test for #39. And also a skipped test showing that we have now introduced the issue #102, ah well.

2022-11-28 23:44 UTC, trevor-scheer requested changes

2022-11-28 23:44 UTC, trevor-scheer commented on README.md
> +- `{ policy: 'do-not-deduplicate'; invalidateDeduplicationKeys?: string[] }`: This is the default behavior for non-GET requests. Always run an actual HTTP request and don't allow other requests to de
```suggestion
- `{ policy: 'do-not-deduplicate'; invalidateDeduplicationKeys?: string[] }`: This is the default behavior for non-GET requests. Always run an actual HTTP request and don't allow other requests to de-duplicate against it. Additionally, invalidate any listed keys immediately: new requests with that `deduplicationKey` will not match any requests that currently exist in the request cache.
```

2022-11-28 23:44 UTC, trevor-scheer commented on README.md
> +  if (request.method === 'GET') {
Just making note that we're probably going to add support for HEAD requests as a part of the work we're doing. We can account for that later when we actually do the work for it (it'll probably make more sense with the typings if we wait too?)

2022-11-28 23:44 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +// within a single RESTDataSource object and is called "deduplication". It is
Would it be more clear to refer to this concept as request deduplication rather than just deduplication? I'm worried it's a little unclear what's being deduped. This comment applies to other places we refer to deduplication.

2022-11-28 23:44 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +  | { policy: 'deduplicate-until-invalidated'; deduplicationKey: string }
What if I want to go from `until-invalidated` to `during-request-lifetime`? There's no way for me to do that without first sending a `do-not-deduplicate` request with proper dedupe keys to invalidate.

Should we be able to also invalidate keys with the `during-request-lifetime` policy?

example series of requests:
`{ policy: 'deduplicate-until-invalidated', deduplicationKey: 'GET https://example.com/api/foo/1' }`
`{ policy: 'deduplicate-during-request-lifetime', deduplicationKey: 'GET https://example.com/api/foo/1' }`
`{ policy: 'deduplicate-during-request-lifetime', deduplicationKey: 'GET https://example.com/api/foo/1' }`

2 & 3 will be deduped. The best I can do right now is this, but 3 won't be deduped even if I want it to be:
`{ policy: 'deduplicate-until-invalidated', deduplicationKey: 'GET https://example.com/api/foo/1' }`
`{ policy: do-not-deduplicate', invalidateDeduplicationKeys: ['GET https://example.com/api/foo/1'] }`
`{ policy: 'deduplicate-during-request-lifetime', deduplicationKey: 'GET https://example.com/api/foo/1' }`

2022-11-28 23:44 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +        }
This seemed like a confusing way to write:
```ts
const result = await thisRequestPromise;
if (policy.policy === 'deduplicate-during-request-lifetime') {
  this.deduplicationPromises.delete(policy.deduplicationKey);
}
return result;
```
But I think the `finally` here is also guaranteeing deduplication (in the face of errors)? A comment about that would be helpful to make sure the intent is fully understood.

2022-11-29 01:20 UTC, glasser commented on src/RESTDataSource.ts
> +        }
Sure, can you suggest a comment? To me `finally` is all about guaranteeing cleanup in the face of errors but I see that this isn't clear.

2022-11-29 01:23 UTC, glasser commented on src/RESTDataSource.ts
> +  | { policy: 'deduplicate-until-invalidated'; deduplicationKey: string }
I guess my question is what the use case is. I'll admit I was mostly thinking of the two deduplicate options as distinct choices where only one or the other would be likely to be interesting to folks (and quite possibly the only folks who'd want `deduplicate-until-invalidated` are people looking for back-compat). I do think the first series "makes sense" — you're deduplicating the first response until invalidated.

ie, I agree there are things you theoretically might want to do to manipulate this cache that the set of primitives provided here doesn't allow for, but is there a use case?

2022-11-29 01:24 UTC, glasser commented on README.md
> +RESTDataSource provides two levels of caching: an in-memory "deduplication" feature primarily used to avoid sending the same GET request multiple times in parallel, and an "HTTP cache" which provides
It's pretty bad grammar for sure.

2022-11-29 02:11 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +        }
It's not something that we use _too_ often and I hadn't really made that semantic connection, but that makes sense.

Helpful comment:
The request promise needs to be awaited here rather than just returned so that we can guarantee the deduplication cache is cleared in the event of an error during the request.

2022-11-29 23:44 UTC, glasser commented on src/RESTDataSource.ts
> +        }
@trevor-scheer Well it's not just errors — if you didn't have the `await` then the cache delete would happen too early...

2022-11-29 23:46 UTC, glasser commented on README.md
> +By default, `RESTDataSource` de-duplicates all outgoing **GET requests** in an in-memory cache, separate from the `KeyValueCache` used for the HTTP response cache. It makes the assumption that two HT
Done (with bold)

2022-11-29 23:46 UTC, glasser commented on README.md
> +RESTDataSource provides two levels of caching: an in-memory "deduplication" feature primarily used to avoid sending the same GET request multiple times in parallel, and an "HTTP cache" which provides
Improved

2022-11-29 23:46 UTC, glasser commented on README.md
> +  if (request.method === 'GET') {
Yeah, later sounds fine

2022-11-29 23:46 UTC, glasser commented on src/RESTDataSource.ts
> +// within a single RESTDataSource object and is called "deduplication". It is
Updated many places including the method and type names

2022-11-29 23:46 UTC, glasser commented
@trevor-scheer OK I think I made all the changes (except the `finally` comment since I didn't think it was quite right).

2022-11-29 23:57 UTC, trevor-scheer approved these changes

2022-11-30 00:03 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +        }
The request promise needs to be awaited here rather than just returned. This ensures that the request completes before it's removed from the cache. Additionally, the use of `finally` here guarantees the deduplication cache is cleared in the event of an error during the request.

2022-11-30 00:07 UTC, merged