Add docs for `didReceiveResponse` replacement
apollographql/datasource-rest pull request #145
Opened 2023-01-20 18:00 UTC by trevor-scheer

It seems like the `didReceiveResponse` hook was fairly used and there's some uncertainty around how to upgrade to v5 now that it's missing. This adds a suggestion in the CHANGELOG and README to override the newly-public `fetch` method (while leveraging the default `fetch` implementation).

Fixes #143
Fixes #109

2023-01-20 23:48 UTC, glasser requested changes

2023-01-20 23:48 UTC, glasser commented on CHANGELOG.md
> +        .then(({ parsedBody, response }) => {
optional: Given that you're showing `async` why not use `await`? Same in the other file.

2023-01-20 23:48 UTC, glasser commented on CHANGELOG.md
> +          return { parsedBody, response };
Hmm, I think it's probably bad to encourage people to deconstruct the `fetch` response and then return the fields (without using a `...rest`) because it makes it harder for us to add fields to the `fetch` return value... Though perhaps doing so is a back-compat problem since it's protected anyway.

2023-01-23 19:29 UTC, trevor-scheer commented on CHANGELOG.md
> +          return { parsedBody, response };
Yeah, good call.

2023-01-23 19:29 UTC, trevor-scheer commented on CHANGELOG.md
> +        .then(({ parsedBody, response }) => {
[3c51518](https://github.com/apollographql/datasource-rest/pull/145/commits/3c515187291fdd40287ffb281f20b74ac36d839d)

2023-01-23 19:29 UTC, trevor-scheer commented on CHANGELOG.md
> +          return { parsedBody, response };
[3c51518](https://github.com/apollographql/datasource-rest/pull/145/commits/3c515187291fdd40287ffb281f20b74ac36d839d)

2023-01-23 20:11 UTC, glasser approved these changes

2023-01-23 20:14 UTC, merged