Fix: Duplicate Content-Type header when Content-Type header is capitalized.
apollographql/datasource-rest pull request #154
Opened 2023-02-01 21:36 UTC by JustinSomers

When a `Content-Type` header exists in a `incomingRequest` object that is passed into the `fetch` function, we will receive a duplicate lowercase `content-type` header.

[Here](https://github.com/apollographql/datasource-rest/blob/9a8b6278d80bc677fa7608ac0c3f065d991a79af/src/RESTDataSource.ts#L486) is where the error occurs in the source code
```
    if (this.shouldJSONSerializeBody(augmentedRequest.body)) {
      augmentedRequest.body = JSON.stringify(augmentedRequest.body);
      // If Content-Type header has not been previously set, set to application/json
      if (!augmentedRequest.headers) {
        augmentedRequest.headers = { 'content-type': 'application/json' };
      } else if (!augmentedRequest.headers['content-type']) {
        augmentedRequest.headers['content-type'] = 'application/json';
      }
```

What my proposed change does is it checks for the capitalized `Content-Type` header, if it exists we create a lowercase `content-type` header and delete the capitalized one.

Alternatively, we could just change the above if statement to:
```
else if (!augmentedRequest.headers['content-type'] && !augmentedRequest.headers['Content-Type']) {
```

2023-02-01 21:36 UTC, apollo-cla commented
@JustinSomers: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-02-01 21:37 UTC, JustinSomers commented on src/RESTDataSource.ts
> +      } else if (augmentedRequest.headers['Content-Type']) {
If we don't want to change the forwarded header, we could alternatively change line 486 to: 

```
 else if (!augmentedRequest.headers['content-type'] && !augmentedRequest.headers['Content-Type']) {
 ```

2023-02-01 22:30 UTC, glasser commented on src/RESTDataSource.ts
> +      } else if (augmentedRequest.headers['Content-Type']) {
This doesn't seem like the right fix, because it doesn't cover `cOnTeNt-TyPe` which is equally legitimate.

2023-02-02 02:32 UTC, AaronMoat commented on src/RESTDataSource.ts
> +      } else if (augmentedRequest.headers['Content-Type']) {
Are we going to have to do:

```
Object.keys(augmentedRequest.headers).map(name => name.toLowerCase()).includes('content-type')
```

2023-02-02 17:08 UTC, JustinSomers commented on src/RESTDataSource.ts
> +      } else if (augmentedRequest.headers['Content-Type']) {
Yeah, that might be the best solution, as lengthy as it is.

2023-02-02 17:09 UTC, JustinSomers commented on src/RESTDataSource.ts
> +      } else if (augmentedRequest.headers['Content-Type']) {
So, do we want to just continue to forward the headers as is? for remap them to a lowercase?

2023-02-06 20:38 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +      } else if (augmentedRequest.headers['Content-Type']) {
My suggestion would be to remap / downcase the header keys as soon as we have the incoming request at the top of the `fetch` method. None of our code should be handling the header keys in a case-sensitive manner (as @glasser has pointed out).

2023-02-06 21:55 UTC, trevor-scheer requested changes
Very minor nitpicks, overall looks good to me!

Can you please add a patch changeset (via the `npx changeset` command) with a brief description of the user-facing impact this change has? (what does it fix)

Thank you!

2023-02-06 21:55 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +        body: JSON.parse(JSON.stringify({ foo: 'bar' })),
The parse + stringify is redundant

2023-02-06 21:55 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +        body: JSON.parse(JSON.stringify({ foo: 'bar' })),
(here and in other instances below)

2023-02-06 21:55 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +    it('adds a application/json content header', async () => {
```suggestion
    it('adds an `application/json` content-type header when none is present', async () => {
```

2023-02-06 21:55 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +    it('adds a application/json content header when no headers are passed in', async () => {
Just being nitty / matching what I suggested above
```suggestion
    it('adds an `application/json` content header when no headers are passed in', async () => {
```

2023-02-06 21:55 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +    it('adds a application/json content header when no content-type headers are passed in', async () => {
I think this is redundant with the first one?

2023-02-06 21:55 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +    let headers: Record<string, string> = {};
```suggestion
    const headers: Record<string, string> = {};
```

2023-02-06 21:55 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +    let headers: Record<string, string> = {};
Maybe rename to `downcasedHeaders` for clarity

2023-02-06 22:21 UTC, trevor-scheer approved these changes

2023-02-06 22:27 UTC, trevor-scheer commented
I'm usually able to trigger a Circle CI run on forks by pushing an empty commit, but that doesn't seem to be working. I opened a [separate branch](https://github.com/apollographql/datasource-rest/commits/trevor/test-ci) (which I'll be deleting) just to see CI pass.

2023-02-06 22:29 UTC, merged