feat: Allow for custom logger to be configured and default to console
apollographql/datasource-rest pull request #186
Opened 2023-04-14 12:31 UTC by js-lowes

`datasource-rest` was using the `console` log for all info messages. This PR Allows overriding the default logger with a custom logger implementation, by default it uses the `console` log.

2023-04-14 12:31 UTC, apollo-cla commented
@js-lowes: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-04-17 17:13 UTC, trevor-scheer requested changes
Can you add a test that demonstrates providing a custom logger to `RESTDataSource` and shows that it's actually used instead of `console`?

2023-04-17 17:13 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +
Will you please use the `Logger` interface from the `@apollo/utils.logger` package instead?

2023-04-17 17:13 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +    this.logger = config?.logger ? config.logger : console;
Nit: just a preference here for nullish coalesce
```suggestion
    this.logger = config?.logger ?? console;
```

2023-04-21 20:22 UTC, js-lowes commented on src/RESTDataSource.ts
> +
updated!

2023-04-21 20:39 UTC, js-lowes commented
@trevor-scheer its ready again :)

2023-04-22 00:19 UTC, trevor-scheer requested changes
Thanks for the README addition! Would you please add a changeset (`npx changeset`) and make this a minor? The message in the created changeset should ideally describe the addition and how users can make use of it (i.e. a code example would be great).

Looking good! I'll get this merged and released once the last few changes are addressed.

2023-04-22 00:19 UTC, trevor-scheer commented on package.json
> +    "@apollo/utils.logger": "^3.0.0",
This should actually be in the dependencies (surprisingly) since the type we use from it is exported by a type from this package.

We also need to stick to the v2.x range for now, since the v3.x utils drop support for node 14 (and we haven't done that in this package yet).

2023-04-22 00:19 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +        this.logger.info(`${label} (${duration}ms)`);
Can we keep this as a call to `.log` instead of changing it to `.info` just to preserve existing behavior?

2023-04-22 00:19 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +
```suggestion
```

2023-04-22 00:21 UTC, trevor-scheer commented on src/__tests__/RESTDataSource.test.ts
> +    expect(dataSource.logger).not.toEqual(console)
Run `npm run prettier-fix`. Our circle checks aren't running against your repo but normally this would be failing for the prettier check.

2023-04-22 15:11 UTC, js-lowes commented on package.json
> +    "@apollo/utils.logger": "^3.0.0",
Good call out, fixed!

2023-04-22 15:13 UTC, js-lowes commented on src/RESTDataSource.ts
> +        this.logger.info(`${label} (${duration}ms)`);
I was just about to swap it back, but unfortunately `.log` does not exist in the `Logger` interface :/

2023-04-22 15:14 UTC, js-lowes commented on src/__tests__/RESTDataSource.test.ts
> +    expect(dataSource.logger).not.toEqual(console)
fixed!

2023-04-22 17:05 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +        this.logger.info(`${label} (${duration}ms)`);
Minor is still good I think. And my mistake on the .log, info is fine!

2023-04-22 18:00 UTC, js-lowes commented on src/__tests__/RESTDataSource.test.ts
> +
fixed

2023-04-22 18:31 UTC, js-lowes commented on src/RESTDataSource.ts
> +        this.logger.info(`${label} (${duration}ms)`);
just pushed, let me know if you need anything else! Thanks for the speedy responses!

2023-04-24 18:56 UTC, trevor-scheer commented
Thanks for your work on this @js-lowes! I'll get this released right away.

2023-04-24 18:57 UTC, trevor-scheer approved these changes

2023-04-24 18:58 UTC, merged