Refactor errorFromResponse
apollographql/datasource-rest pull request #246
Opened 2023-08-26 13:39 UTC by lotmek

## Description
- Turn `url` and `request` into optional parameters
- Refactor the way to add `code` in the `extensions` object

2023-08-28 17:06 UTC, trevor-scheer commented
I think this is a good change, especially since the concrete method here doesn't make use of those params. Thinking out loud because at first glance, this seems like a breaking change. Explaining why it _isn't_.

The signature of the method does not impose any requirements on the signature in concrete class definitions that extend `RESTDataSource` and override this method. That means an overridden `errorFromResponse` method can have _any_ signature, meaning users who currently extend `errorFromResponse` will not be affected by this change. This isn't the first time I've "discovered" this, but usually surprises me.

Additionally, users currently calling this method are unaffected - they won't see any change for already including parameters which become optional (though the other direction optional -> required would be problematic).

Related thought worth capturing that doesn't impact this PR:
`throwIfResponseIsError` and `errorFromResponse` are "linked" by their types. If you override `errorFromResponse` and provide a different signature (specifically, an extended one), you're going to be surprised when `throwIfResponseIsError` calls your method. I'm actually not sure how to fix this.

```ts
class MyDataSource extends RESTDataSource {
  override async errorFromResponse({
    response,
    parsedBody,
  }: {
    response: FetcherResponse;
    parsedBody: string;
    extra: string; // not a TS error, but this won't exist if I don't override `throwIfResponseIsError`
  }): Promise<GraphQLError> {
    return new GraphQLError('...');
  }
}
```

2023-08-28 17:11 UTC, trevor-scheer requested changes
Please add a `patch` changeset describing your changes. You can run the changeset tool via `npx changeset` and follow the prompts.

2023-08-28 17:11 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +        ...(code && { code }),
This change looks correct to me but without a test validating your change I'd rather just leave it as is. I don't think the ternaries here are so complex that it necessitates cleanup.

My preference is to revert this, but if you insist then I'd require a test.

2023-08-28 20:20 UTC, lotmek commented on src/RESTDataSource.ts
> +        ...(code && { code }),
Hi @trevor-scheer the codes are already tested in those two cases:
- [throws a FORBIDDEN error when the response status is 403](https://github.com/apollographql/datasource-rest/blob/f6106f5e417fb85656643d9dcd15505e3195368e/src/__tests__/RESTDataSource.test.ts#L1596-L1618)
- [throws an UNAUTHENTICATED error when the response status is 401](https://github.com/apollographql/datasource-rest/blob/f6106f5e417fb85656643d9dcd15505e3195368e/src/__tests__/RESTDataSource.test.ts#L1572C11-L1594)

I am just adding an extra assertion in this third test case ([throws an ApolloError when the response status is 500](https://github.com/apollographql/datasource-rest/blob/f6106f5e417fb85656643d9dcd15505e3195368e/src/__tests__/RESTDataSource.test.ts#L1620-L1641)), just to make sure the property is not being added:
https://github.com/apollographql/datasource-rest/blob/410213bb2caadb2860ef2bbfa918e0e7011d7d82/src/__tests__/RESTDataSource.test.ts#L1641

2023-09-12 17:40 UTC, trevor-scheer approved these changes

2023-09-12 17:41 UTC, merged