use lodash cloneDeep to clone parsed body
apollographql/datasource-rest pull request #270
Opened 2023-10-15 08:49 UTC by Sean-Y-X

`JSON.parse(JSON.stringify())` is a bad way to clone objects.

There are many reasons why it is bad. For example: [](https://medium.com/@pmzubar/why-json-parse-json-stringify-is-a-bad-practice-to-clone-an-object-in-javascript-b28ac5e36521)

I understand this method can be overridden but I don't think we should use a flawed approach as the default.

2023-10-15 08:49 UTC, apollo-cla commented
@Sean-Y-X: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-10-17 19:40 UTC, trevor-scheer requested changes
Just a couple suggestions. Thanks for the PR!

2023-10-17 19:40 UTC, trevor-scheer commented on src/RESTDataSource.ts
> +    return cloneDeep(parsedBody);
```suggestion
    // consider using `structuredClone()` when we drop support for Node 16 
    return cloneDeep(parsedBody);
```

2023-10-17 19:40 UTC, trevor-scheer commented on package.json
> +    "@types/lodash.clonedeep": "^4.5.7",
The change I'm suggesting here requires a rerun of `npm i` to update the lockfile.

```suggestion
    "@types/lodash.clonedeep": "4.5.7",
```

2023-10-17 19:40 UTC, trevor-scheer commented on .changeset/fluffy-ants-appear.md
> +use lodash to clone parsed body
```suggestion
---
'@apollo/datasource-rest': patch
---

Use lodash's `cloneDeep` to clone parsed body instead of `JSON.parse(JSON.stringify(...))`
```

2023-10-17 21:03 UTC, Sean-Y-X commented
@trevor-scheer thanks for your suggestions!

2023-10-17 21:22 UTC, trevor-scheer approved these changes

2023-10-17 21:23 UTC, merged